### PR TITLE
feat: add requestOptions for schema-reg client

### PR DESCRIPTION
**Pull request by BeyerJC**
Adds support for "auth" and "timeout" options to be set for the guzzle client.
This feature is needed when using schema-registry from confluent cloud for example.

The list could be extended by simply adding more options to the array if needed. 

Configuration option and validation were copied from https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/DependencyInjection/Configuration.php 
so credits to them.

### CODE REVIEW

**Comment by BeyerJC** [comment]
@KonstantinCodes Ping :-)

**Review by KonstantinCodes — CHANGES_REQUESTED** [review]
Looks really good! Would you just remove the blank lines between the use statements?
Then it's good to merge

**Comment by BeyerJC** [comment]
> Looks really good! Would you just remove the blank lines between the use statements? Then it's good to merge

Hey @KonstantinCodes , thanks for the reply! The blank lines are done by php-cs-fixer. If i remove them, csfixer will add them again. I thought it would add blank lines because use function/const/import is mixed but it really likes to sort it that way.

Should i just do it manually ?

**Comment by KonstantinCodes** [comment]
Haha that's super weird 😄
But if it's from phpcsfixer, it can stay. Thanks

**Pull request merged**
